### ISSUE TITLE
Improvement of profile page UI

### ISSUE THREAD

**Issue by souro18** [UdacityFrontEndScholarship/task-master#115]
want to work on this.

**Comment by bhaskarSingh** [comment]
What exactly do you want to work on, can be more specific

**Comment by shashank-sharma** [comment]
@souro18 Can you please be more specific as if what you are trying to work on so that we can decide and let you work on it. So please add some meaningful text in description.
At the same time please refer to [Contribution guidelines](https://github.com/UdacityFrontEndScholarship/task-master/blob/master/CONTRIBUTING.md).
Why we are saying this ?
Because it will help us to evaluate your work and see if it is worth working or not.

**Comment by souro18** [comment]
Proposals:
For add goal box:
- separate field for task title and description.
- add task deadline date , task-priority(drop down consisting high,medium,low which we can use to set different background colours for cards),alarm time
- alarm type(drop down consisting daily,weekly,monthly) along with other functionalities mentioned in mockup
For cards:
- add scroll feature
- add task date along with time
- switch button (pending and done) user can mark a task as done if  he has completed task before time also we can sort task on basis of this when back-end will be implemented like all the pending task will come first then all the completed task.
- use less number of colour in page
@Rajrox97 @pbiswas101

**Comment by pbiswas101** [comment]
Great @souro18 
Then you keep working on this features that you've enlisted especially the _color usage_ so that it aligns with the overall theme while also keeping variations in different tasks!

**Comment by Manda7rsnt** [comment]
I would also want to work on this  :)
