### ISSUE TITLE
Homepage doesn't Looks Attractive, Check Out this!

### ISSUE THREAD

**Issue by sskanishk** [UdacityFrontEndScholarship/task-master#120]
# Check Out Both.!
![webpage](https://user-images.githubusercontent.com/29313203/39068373-bd38c60c-44f9-11e8-905a-2fa0f744ffe3.png)

![screen shot 2018-04-20 at 8 29 23 pm](https://user-images.githubusercontent.com/29313203/39058527-b8ba6e16-44d9-11e8-8c35-6a25b404d1de.png)

**Comment by shashank-sharma** [comment]
Hi @sskanishk 
Your issue is related to enhancement in current home page. But can you please elaborate a bit more about your issue ?

I mean what are the components of homepage which you dislike right now (with reason) and what you are planning to fix it. I hope it is reasonable to ask these things.

**Comment by bhaskarSingh** [comment]
The new design does look better, I think we should go with it

**Comment by Rajrox97** [comment]
@bhaskarSingh @sskanishk The new design may look better, but we are aware that our background images are not up to the mark. So we never know how the background image will look when we come up with the new background image. 

And there will be some modification of the homepage , but some. 

As, @shashank-sharma shashank pointed out, can you please  elaborate a bit more about your issue?

**Comment by sskanishk** [comment]
**Sure!** @shashank-sharma @bhaskarSingh @Rajrox97 
# we can change the contact box from dominating black to white.
![screen shot 2018-04-22 at 2 47 38 am](https://user-images.githubusercontent.com/29313203/39088902-745ba0be-45d8-11e8-9b78-95d7b1b42e5d.png)

**Comment by shashank-sharma** [comment]
@sskanishk 
In future I suggest you open issue related to specific component rather than opening it for whole page like this here you are talking about Homepage. 
The problem is that you created a new UI for contact form but there is also one issue which states that the button size should be small. 
Now if I accept either one of your PR then it will conflict with your changes which is bad.

**Comment by sskanishk** [comment]
Next time I will take care of it...  @shashank-sharma
