### ISSUE TITLE
Backend for dashboard 

### ISSUE THREAD

**Issue by Saichethan** [UdacityFrontEndScholarship/task-master#125]
How are we going to authenticate a user and how will we generate automatically after signup what is the backend for this

**Comment by shashank-sharma** [comment]
Hi @Saichethan 
Currently there other moderators who are experienced in PHP will work on this.
Without any proper structure/layout we can't open this issue right now. Please currently open issues related to Frontend only and then later when our Frontend work is almost done then we will start implementing it.
Since this issue is not related to any Frontend work, I am closing this issue. For further discussion please do so in our Slack channel. I hope this clears your doubt.
