### ISSUE TITLE
Why are we using templates all of a sudden?

### ISSUE THREAD

**Issue by user501254** [UdacityFrontEndScholarship/task-master#17]
Thought we had already settled on folder structure and Materialize CSS/JS framework in https://github.com/UdacityFrontEndScholarship/task-master/issues/10. Hence PR https://github.com/UdacityFrontEndScholarship/task-master/pull/12 was merged.

However the commits a26d0c5e40234cfa6b628167c76d14410e02ca14, 0ae40425abb61973ed1676431754e01e40561111, 0bee36b98da8156ef13d3451428d8b1c55c3d480 overwrite those changes made by the PR. 
Now as a result all the files for Materialize framework are gone and replaced with the "[Grayscale](https://github.com/BlackrockDigital/startbootstrap-grayscale)" template.

**Comment by Rajrox97** [comment]
The changes that you had done resulted in a broken index.html file. The file structure was organised. Yes, It was more organised than we had made it. But i am guessing that you forgot to test it.

As a result, the CSS we had linked to the file was broken and the page was broken.

Hope this helps. Let me know if you have any more questions. :D

**Comment by user501254** [comment]
Hi @Rajrox97 

Thanks for reverting back. However there was no content within the `index.html` which was present in the PR, only links to the CSS and JS files. It was supposed to be modified accordingly. It wasn't broken.
Also before the merge happened the repo did not have any index.html file in the root directory.

**Comment by Rajrox97** [comment]
Hi @user501254 

I understand that you didn't change the content of the previous index.html and organised the folders for us ,for which we are grateful  .But , as a sidenote, from now on, when you send PR , please test it before running. :) It will be easier for us both. 

Also, as an update, we decided to streamline the directory because a lot of people were having trouble understanding the file structure. 

We also made MATERIALIZECSS compulsory replacing the  bootstrap version. Let me know if you have any other questions :)
