### ISSUE TITLE
Add navbar hover effects, logo effect, logo scrollTop animate

### ISSUE THREAD

**Issue by vikkrantxx7** [UdacityFrontEndScholarship/task-master#182]
- Logo effect
- [ ] ![task1](https://user-images.githubusercontent.com/37444378/39957162-d11f2044-560b-11e8-974a-0627fbe42dfe.gif)
- Hover effect
- [ ] ![task2](https://user-images.githubusercontent.com/37444378/39957170-1c60184c-560c-11e8-95e9-96ab0bfa2729.gif)
- Hover effect
- [ ] ![task3](https://user-images.githubusercontent.com/37444378/39957177-2b413a8a-560c-11e8-920d-271b71b716e8.gif)
- Logo scrollTop animate
- [ ] ![task4](https://user-images.githubusercontent.com/37444378/39957181-32c53cac-560c-11e8-8d1b-9322b9736c33.gif)

**Comment by vikkrantxx7** [comment]
#Rajrox97 please try to give reasons on closing.

**Comment by Rajrox97** [comment]
We had announced some days ago that we won't be accepting PRs except the
ones that are already assigned to some folks. It's because our backend is
being deployed and we don't want to make major changes here anymore.

And usually when I close an issue or PR I label it . Since it's an
enhancement that you are making and not a major fix , I guess closing down
the issue means the enhancement is best not implemented at present. I hope
this makes sense. Happy coding  . :)
